#define FORCE_NKRO
#define USB_POLLING_INTERVAL_MS 1   // Set 1000Hz polling rate

#ifdef RGB_MATRIX_ENABLE
    #define RGBLIGHT_HUE_STEP 8
    #define RGBLIGHT_SAT_STEP 8
    #define RGBLIGHT_VAL_STEP 8

    #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
    #define RGB_DISABLE_WHEN_USB_SUSPENDED
#endif